### ISSUE TITLE
How to localize hero name?

### ISSUE THREAD

**Issue by kxxoling** [odota/ui#847] opened 2017-03-27 17:41 UTC
I got a hero filter in [match log page](https://www.opendota.com/matches/3081663505/log), but found that all the hero names are listed in English even I set language to zh-CN:

![image](https://cloud.githubusercontent.com/assets/1227139/24369653/432835ac-1357-11e7-891d-28fab689afb9.png)

I tried to find where the heroes data stored in code, but found nothing. So what can I do to help this component be translated?

**Comment by howardchung** [comment] 2017-03-28 02:27
This is a duplicate of #411 .  Basically we pull the data from Valve endpoints.  Some of it is available in other languages, but we currently aren't using those endpoints yet.

**Closed by howardchung** 2017-03-28 02:27 UTC
