### ISSUE TITLE
Multiple items cause time bug.

### ISSUE THREAD

**Issue by alessandrocls** [odota/ui#764] opened 2017-03-01 02:00 UTC
I just had a game where an enemy sniper bought 2 mjollnirs. When I opened the match data on opendota it said that he got both simultaneously. However, a quick check on the purchases tab show that he actually got the second mjollnir much later in the game.

OS: Windows 10
Browser: Chrome Version 56.0.2924.87
Link: 
Wrong time: https://www.opendota.com/matches/3027317162/overview
Correct time: https://www.opendota.com/matches/3027317162/purchases

**Comment by howardchung** [comment] 2017-03-01 03:03
This is a duplicate of #437 .  Unfortunately there isn't a fix yet (this is caused by the overview relying on the first purchased time).

**Closed by howardchung** 2017-03-01 03:03 UTC
