### ISSUE TITLE
HTML Title tag should identify each page

### ISSUE THREAD

**Issue by thomassross** [odota/ui#589] opened 2016-12-12 17:25 UTC
For example if I'm on `thomas`'s OpenDota page, maybe the title should be `thomas - OpenDota`? All of the titles are `OpenDota - Dota 2 statistics` right now making it very confusing when switching between multiple tabs.

**Comment by howardchung** [comment] 2016-12-12 17:29
duplicate of #422 (but yes, we should fix this)

**Closed by howardchung** 2016-12-12 17:29 UTC
